feat: add compensation matrix to drive command
tidewise/drivers-orogen-deep_trekker pull request #13
Opened 2023-05-30 01:31 UTC by seixasxbr

2023-05-30 12:57 UTC, jhonasiv commented on deep_trekker.orogen
> +    # and to add offset commands
Add that it MUST be 6x7 with and try to describe the expectations for each element, something like 
[ Tx Ty Tz Rx Ry Rz OffX ] -> for X axis
[ Tx Ty Tz Rx Ry Rz OffY] -> for Y axis
and so on

2023-05-30 12:57 UTC, jhonasiv commented on tasks/RevolutionTask.hpp
> +        base::commands::LinearAngular6DCommand compensateDriveCommand(base::commands::LinearAngular6DCommand drive_command);
make drive_command const&

2023-05-30 18:49 UTC, jhonasiv requested changes

2023-05-30 18:49 UTC, jhonasiv commented on tasks/RevolutionTask.cpp
> +        compensated_drive_matrix(1, 0), compensated_drive_matrix(2, 0);
Try this:
```
compensated_drive.linear = compensated_drive_matrix.col(0).head(3);
```

2023-05-30 18:49 UTC, jhonasiv commented on tasks/RevolutionTask.cpp
> +            compensated_drive,
remove all traces of the buoyancy compensation parameter, otherwise it will affect the already compensated_drive parameter again

2023-05-31 14:14 UTC, seixasxbr commented
@jhonasiv approved this

2023-05-31 14:14 UTC, merged